### PR TITLE
Interface changes on inq_varname

### LINKED ISSUE #56: Overflow issue caused by strncpy
Commit 2406c8b in master branch caches file and variable names in PIO. It added code like below:
```
char my_name[PIO_MAX_NAME + 1];
...
strncpy(name, my_name, PIO_MAX_NAME);
```
Here, name is a passed in char array (e.g. from ACME Fortran code). The length of the name array can be short (in one ACME test it is only 32)

According to the link below
http://www.cplusplus.com/reference/cstring/strncpy
> char * strncpy ( char * destination, const char * source, size_t num );
> Copies the first num characters of source to destination. If the end of the source C string (which is signaled by a null-character) is found before num characters have been copied, destination is padded with zeros until a total of num characters have been written to it.

This indicates that overflow could occur if num is larger than the length of destination.

The following code can simulate a failed ACME test due to this overflow issue
```
/* test_strncpy.c */
#include <stdio.h>
#include <string.h>

#define PIO_MAX_NAME 256

int main ()
{
  char name[32]; /* ACME Fortran code passes in a buffer whose length is only 32 */
  char my_name[PIO_MAX_NAME + 1] = "DMS"; /* Buffer length is 257, actual length is 3 */

  /* Overflow: name is padded with zeros until a total of 256 characters have been written to it. */
  strncpy(name, my_name, PIO_MAX_NAME);

  puts(name);

  return 0;
}
```
Address Sanitizer can show the overflow
```
gcc test_strncpy.c -fsanitize=address -fno-omit-frame-pointer -g
./a.out
ERROR: AddressSanitizer: stack-buffer-overflow on address xxxxxxxx
WRITE of size 256 at xxxxxxxx thread T0
```

### PR DESCRIPTION
**Pull request by dqwu**
Updating PIO2 C and Fortran interfaces related to inq_varname.

For master branch, there is a known buffer overflow caused by
strncpy() in PIOc_inq_var. Some ACME tests/cases have failed
due to that issue.

PIOc_inq_varname and PIOc_inq_var now need to know the size
of the user buffer, and use that information when copying variable
name to the buffer.

Fixes #56

### CODE REVIEW

File: src/clib/pio_nc.c [hunk 1]
```diff
@@ -847,9 +847,9 @@ int PIOc_inq_var(int ncid, int varid, char *name, nc_type *xtypep, int *ndimsp,
             }
             if (!ierr)
                 ierr = ncmpi_inq_var(file->fh, varid, my_name, xtypep, ndimsp, (dimidsp)?dimidsp:tmp_dimidsp, nattsp);
-            if (!ierr && name)
+            if (!ierr && name && max_namelen > 0)
             {
-                strncpy(name, my_name, PIO_MAX_NAME);
+                strncpy(name, my_name, (max_namelen < PIO_MAX_NAME) ? max_namelen : PIO_MAX_NAME);
```
Comment (jayeshkrishna) [inline src/clib/pio_nc.c]: Instead of this logic it would be better to have an assert to check that namelen <= PIO_MAX_NAME+1, change the size of cached name to PIO_MAX_NAME+1, and change the name of the arg from max_namelen to just namelen.

Comment (dqwu) [reply src/clib/pio_nc.c]: Thanks, I have made the code changes and rebased the feature branch.
